# Generated by Django 4.1.3 on 2022-12-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temp', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('time', models.TextField()),
            ],
        ),
    ]
